dpla_local_map = {'Cuba': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Cuban revolution': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Spanish American War': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Puerto Rico': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Haiti': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Bahamas': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Trinidad': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Tobago': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Virgin Islands': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Jamaica': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Dominican Republic': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Hispaniola': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Dominica': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Martinique': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Saint Lucia': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Saint Vincent': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Grenada': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Barbados': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Turks and Caicos': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Cayman Islands': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Anguilla': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Antigua': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Barbuda': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Redonda': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Saint Martin': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Montserrat': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Guadeloupe': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Saint Kitts': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Saba': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Sint Eustatius': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Colonial': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Colonialism': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Revolution': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Independence': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279"),
                                   ("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'Slave rebellions': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Indentured labour': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Abolition': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279"),
                                ("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'Abolitionist': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279"),
                                   ("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'Sugar': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279"),
                            ("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Tourism': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Ports': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Shipping': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Export': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Guantanamo Bay': [("Caribbean Area", "http://id.loc.gov/authorities/subjects/sh85020279")],
                  'Emmett Till': [("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'Civil Rights': [("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'Human rights': [("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'Vaclav Havel': [("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'Activists': [("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'Activism': [("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'Advocacy': [("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'Civic': [("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'Humanitarian': [("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'Humanitarianism': [("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'African American Rights': [
                      ("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'Segregation': [("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'Slavery': [("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'Juneteenth': [("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'Jim Crow': [("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'Women’s rights': [("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'Voting': [("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'Suffrage': [("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'Suffragette': [("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'National Organization for Women': [
                      ("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'NOW': [("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'Equal Rights Amendments': [
                      ("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'Feminism': [("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'LGBTQ': [("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'LGBT': [("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'Lesbian, Gay, Bisexual, and Transgender Studies': [
                      ("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'Americans with Disabilities Act': [
                      ("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'ADA': [("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'Protests': [("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'Diplomacy': [("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'Abraham Lincoln': [("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'Suzanne Vega': [("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'Madeleine Albright': [("Human rights", "http://id.loc.gov/vocabulary/graphicMaterials/tgm005213")],
                  'Peat': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Hydrology': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Drainage': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Reclamation': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Runoff': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Groundwater': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Ecology': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Geology': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Geography': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Biology': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Biologist': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Birds': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Botany': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Botanical': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Phosphorus': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Rainfall': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Fish': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Marine': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Wetland': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Seagrass': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Canal': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'River': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Lake': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Creek': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Ocean': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Shoreline': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Dredge': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Dredging': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Mangrove': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Pine': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Cypress': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Hunting': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Flood': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Hurricane': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Beach': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Coast': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Coastal': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Reef': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Coral': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Erosion': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Fire': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Aquifer': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Palm': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Logging': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Citrus': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Oil': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Environmental protection': [
                      ("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Parks': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'National Park': [
                      ("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'State Park': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Okeechobee': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Everglades': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Dry Tortugas': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Biscayne': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Big Cypress': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Fort Clinch': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Paynes Prairie': [
                      ("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Alafia River': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Alexander Springs': [
                      ("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Marjory Stoneman Douglas': [
                      ("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Marjorie Carr': [
                      ("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'David Fairchild': [
                      ("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Ernest Coe': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Claude Matlack': [
                      ("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Internal Improvement': [
                      ("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Public Works': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Public Lands': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Springs': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Nature': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")],
                  'Wildlife': [("Landscape protection", "http://id.loc.gov/vocabulary/graphicMaterials/tgm002462")]
                  }

# def subject_mapper():
#     for item in dpla_local_map:
#         yield item
