dpla_local_map = {'Cuba': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Cuban revolution': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Spanish American War': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Puerto Rico': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Haiti': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Bahamas': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Trinidad': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Tobago': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Virgin Islands': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Jamaica': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Dominican Republic': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Hispaniola': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Dominica': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Martinique': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Saint Lucia': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Saint Vincent': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Grenada': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Barbados': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Turks and Caicos': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Cayman Islands': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Anguilla': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Antigua': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Barbuda': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Redonda': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Saint Martin': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Montserrat': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Guadeloupe': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Saint Kitts': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Saba': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Sint Eustatius': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Colonial': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Colonialism': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Revolution': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Independence': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279'),
                                   ('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'Slave rebellions': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Indentured labour': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Abolition': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279'),
                                ('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'Abolitionist': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279'),
                                   ('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'Sugar': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279'),
                            ('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Tourism': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Ports': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Shipping': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Export': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Guantanamo Bay': [('Caribbean Area', 'http://id.loc.gov/authorities/subjects/sh85020279')],
                  'Emmett Till': [('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'Civil Rights': [('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'Human rights': [('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'Vaclav Havel': [('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'Activists': [('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'Activism': [('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'Advocacy': [('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'Civic': [('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'Humanitarian': [('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'Humanitarianism': [('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'African American Rights': [
                      ('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'Segregation': [('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'Slavery': [('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'Juneteenth': [('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'Jim Crow': [('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'Women’s rights': [('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'Voting': [('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'Suffrage': [('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'Suffragette': [('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'National Organization for Women': [
                      ('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'NOW': [('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'Equal Rights Amendments': [
                      ('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'Feminism': [('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'LGBTQ': [('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'LGBT': [('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'Lesbian, Gay, Bisexual, and Transgender Studies': [
                      ('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'Americans with Disabilities Act': [
                      ('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'ADA': [('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'Protests': [('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'Diplomacy': [('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'Abraham Lincoln': [('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'Suzanne Vega': [('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'Madeleine Albright': [('Human rights', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm005213')],
                  'Peat': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Hydrology': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Drainage': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462'),
                               ('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Reclamation': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Runoff': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Groundwater': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Ecology': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Geology': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Geography': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Biology': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Biologist': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Birds': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Botany': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Botanical': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Phosphorus': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Rainfall': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Fish': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Marine': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Wetland': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Seagrass': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Canal': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'River': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Lake': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Creek': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Ocean': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Shoreline': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Dredge': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Dredging': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Mangrove': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Pine': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Cypress': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Hunting': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Flood': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Hurricane': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Beach': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Coast': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Coastal': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Reef': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Coral': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Erosion': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Fire': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Aquifer': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Palm': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Logging': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Citrus': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462'),
                             ('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Oil': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Environmental protection': [
                      ('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Parks': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462'),
                            ('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'National Park': [
                      ('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'State Park': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Okeechobee': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Everglades': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Dry Tortugas': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Biscayne': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Big Cypress': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Fort Clinch': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Paynes Prairie': [
                      ('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Alafia River': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Alexander Springs': [
                      ('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Marjory Stoneman Douglas': [
                      ('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Marjorie Carr': [
                      ('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'David Fairchild': [
                      ('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Ernest Coe': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Claude Matlack': [
                      ('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Internal Improvement': [
                      ('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Public Works': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Public Lands': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Springs': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Nature': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Wildlife': [('Landscape protection', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm002462')],
                  'Transportation & Travel': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Travel': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Hotels': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Restuarants': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Taverns (Inns)': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Bars (Drinking establishment)': [
                      ('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Voyages and travels': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Railroads': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Automobile travel': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Recreation and tourism': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Outdoor recreation': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Historic sites': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Recreation areas': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Sports and Recreation': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Park facilities': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Transportation': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Parks--Public use': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Public lands': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Vacations': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Vacation homes': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Resorts': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Beaches': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Boardwalks': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Swimming': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Sunbathing': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Landscape and Nature': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Leisure': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Air travel': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Airports': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Boats and boating': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'National parks and reserves': [
                      ('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'National parks & reserves': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'State and National Parks': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Cruises': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Cruise ships': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Disney': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Theme parks': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Sightseeing business': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Tourist attractions': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Parades & processions': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Sightseeing': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Florida--Tours': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Tours': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Travel--Guidebooks': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Package tours--Guidebooks': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Air travel--Guidebooks': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Tour Guides': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Timetables': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Tourism--Guidebooks': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Travel Agents': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Water taxis': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Florida--Description and travel': [
                      ('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Wildlife-related recreation': [
                      ('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Railroad companies': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Swimming pools': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Botanical gardens': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Cypress Gardens (Winter Haven, Fla.)': [
                      ('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Cypress Gardens (Winter Haven, Florida)': [
                      ('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Gardens': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915')],
                  'Plantations': [('Tourism', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm010915'),
                                  ('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Farm': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Farmers': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Farm life': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Ditches': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Farms--Florida': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Land use': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Oxen': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Agricultural laborers': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Country life': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Crops': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Field Crops': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Barns': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Farm buildings': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Agriculture--Florida': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Carts and wagons': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Cattle': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Oranges': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Orange growers--Florida': [
                      ('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Fruit trees--Florida': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Limes': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Lemons': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Grapefruits': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Home demonstration work': [
                      ('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Home economics, Rural': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Citrus fruit industry': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Fish as food': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Forest products industry': [
                      ('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Livestock': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Mines and mineral resources': [
                      ('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Farming': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Farming tools': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Plows': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Horses': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Harvest festivals': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Agriculture and Resource Economics': [
                      ('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Rodeos': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Cowboys': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Bulls': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Rodeo clowns': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Calves': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Horsemanship': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Bull riding': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Bronc riding': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Calf roping': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Cattle pens': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Rodeo animals': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Rodeo Riders': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Croplands': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Seeds': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Nursery stock': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Agriculture and food production': [
                      ('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Seed industry and trade': [
                      ('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Agricultural implements': [
                      ('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Tractors': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Nurseries (Horticulture)': [
                      ('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Agricultural sites': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Poultry': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Fruit trees': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Farm Equipment': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Agricultural machinery': [
                      ('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Farm tractors': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Harvesting': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Plantations--Florida': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Cotton industry': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Sharecropping': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Plantation workers': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Sugar plantations': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Antebellum Florida, 1845-1861': [
                      ('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Tobacco': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Tobacco products': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')],
                  'Tobacco industry': [('Agriculture', 'http://id.loc.gov/vocabulary/graphicMaterials/tgm000152')]
                  }
